### ISSUE TITLE
Grunt plugin (if anyone needs it)

### ISSUE THREAD

**Issue by albertboada** [thesam/angular-jsx#5]
Needed it for a project, so I adapted your Gulp plugin to Grunt, just in case anyone else needs it:
https://github.com/albertboada/grunt-angular-jsx
Hope you don't mind!

Awesome work, btw, I love having my templates defined in the same component file :)

**Comment by thesam** [comment]
That's great! I don't mind at all. :) I've added a link to your Grunt plugin in the README.

**Comment by albertboada** [comment]
Super! Thanks!
